default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  url: postgresql://postgres:postgres@localhost:5432/api_rswag_development?encoding=utf8&pool=5&timeout=5000

staging:
  <<: *default

test:
  <<: *default
  url: postgresql://postgres:postgres@localhost:5432/api_rswag_test?encoding=utf8&pool=5&timeout=5000


production:
  <<: *default